project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - installation.qmd
    - motivations.qmd
    - methodological-approach.qmd
    - course-structure-and-content.qmd
    - foundational-concepts-in-probability-and-statistics/index.ipynb
    - foundational-concepts-in-probability-and-statistics/random-variables-and-probability-distributions.ipynb
    - foundational-concepts-in-probability-and-statistics/statistical-inference.ipynb
    - island-effects/index.qmd
    - island-effects/model-definition.ipynb
    - island-effects/model-fitting-and-comparison.ipynb
    - projective-content/index.qmd
    - projective-content/inferentially-defined-classes-of-predicates.qmd
    - projective-content/model-definition.ipynb
    - projective-content/model-fitting-and-comparison.ipynb
    - selection/index.qmd
    - selection/a-brief-primer-on-gradient-based-optimization.qmd
    - selection/model-definition.ipynb
    - selection/model-fitting-and-comparison.ipynb
    - thematic-roles/index.qmd
    - thematic-roles/learning-distributional-representations.ipynb
    - thematic-roles/model-definition.ipynb
    - thematic-roles/model-fitting-and-comparison.ipynb


website:
  title: "Representation Learning for Syntactic and Semantic Theory"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - installation.qmd
      - motivations.qmd
      - methodological-approach.qmd
      - course-structure-and-content.qmd
      - section: "Foundational Concepts in Probability and Statistics"
        contents:
          - foundational-concepts-in-probability-and-statistics/index.ipynb
          - foundational-concepts-in-probability-and-statistics/random-variables-and-probability-distributions.ipynb
          - foundational-concepts-in-probability-and-statistics/statistical-inference.ipynb
      - section: "Module 1: Island Effects"
        contents:
          - island-effects/index.qmd
          - island-effects/model-definition.ipynb
          - island-effects/model-fitting-and-comparison.ipynb
      - section: "Module 2: Projective Content"
        contents:
          - projective-content/index.qmd
          - projective-content/inferentially-defined-classes-of-predicates.qmd
          - projective-content/model-definition.ipynb
          - projective-content/model-fitting-and-comparison.ipynb
      - section: "Module 3: Selection"
        contents:
          - selection/index.qmd
          - selection/a-brief-primer-on-gradient-based-optimization.qmd
          - selection/model-definition.ipynb
          - selection/model-fitting-and-comparison.ipynb
      - section: "Module 4: Thematic Roles"
        contents:
          - thematic-roles/index.qmd
          - thematic-roles/learning-distributional-representations.ipynb
          - thematic-roles/model-definition.ipynb
          - thematic-roles/model-fitting-and-comparison.ipynb

format:
  html:
    theme: lux
    highlight-style: oblivion
    css: styles.css
    toc: true

filters:
  - include-code-files
  - line-highlight

comments:
  giscus: 
    repo: aaronstevenwhite/representation-learning-course



