---
title: "Module 4: Thematic Roles"
bibliography: ../references.bib
---

::: {.callout-tip}
## Reading

**Data:** @reisinger_semantic_2015 and @white_universal_2020 on collecting corpus annotations of the proto-role properties proposed by @dowty_thematic_1991. We will use the Universal Decompositional Semantics (UDS) dataset [v2.0 @gantt_decomposing_2022], which is packaged with the decomp toolkit, available [here](https://github.com/decompositional-semantics-initiative/decomp). 

**Theory:** @levin_argument_2005[Ch. 2] on the explanatory role of generalized thematic roles.
:::

In this fourth and final module of the course, we are going to focus on introducing nontrivial structure into the representations we learn from annotated corpus data while retaining the benefits of mixed effects models. As a case study, we're going to be interested in the question–discussed by @levin_argument_2005[Ch. 2]–of what sorts of representations determine the relationship between individual thematic roles and syntactic positions.